// SPDX-License-Identifier: Unlicense

pragma solidity ^0.8.20;

import '@openzeppelin/contracts/utils/Base64.sol';

/**
 * @dev Renders a Radioactive Punk as a static SVG, fully on-chain.
 *
 *      Reads each punk's trait bytes from the deployed
 *      RadioactivePunksBytesHyperstructure, picks its layers with the same
 *      rules as the original renderer's JS, stacks them into a 24x24 grid and
 *      writes one SVG path per color. Layer art comes from the
 *      RadioactivePunksLayerData chunks, generated by
 *      scripts/pack-layer-data.js from the original renderer's SVG
 *      spritesheet (see that script for the byte layout).
 *
 *      Data is read straight from contract code with EXTCODECOPY, copying
 *      only the index and the ~11 layers a punk uses.
 *
 *      tokenSVG(id)   -> <svg ...>...</svg>
 *      tokenImage(id) -> data:image/svg+xml;base64,...
 */
contract RadioactivePunksImage {
  address public immutable traits;
  address public immutable layerData1;
  address public immutable layerData2;

  // layer data bytes held by layerData1 (its code minus the STOP byte)
  uint256 private immutable split;

  // RadioactivePunksBytesHyperstructure keeps its trait bytes as one block
  // starting at this byte of its runtime code
  uint256 private constant TRAITS_CODE_OFFSET = 182;
  bytes15 private constant TOKEN_0_TRAITS = 0x010100000400000003000200000000;

  error TokenDoesNotExist();
  error WrongTraitsContract();

  // trait byte positions, see RadioactivePunksRenderer's LOOKUP TABLE
  uint256 private constant GLOW = 0;
  uint256 private constant MORTALITY = 1;
  uint256 private constant HEAD = 3;

  bytes private constant SVG_START =
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" shape-rendering="crispEdges"><rect width="24" height="24" fill="#1f2e3d"/>';

  // longest possible output: every cell its own run and its own color
  uint256 private constant MAX_SVG_LENGTH = 25000;

  constructor(address traits_, address layerData1_, address layerData2_) {
    traits = traits_;
    layerData1 = layerData1_;
    layerData2 = layerData2_;
    split = layerData1_.code.length - 1;
    if (bytes15(_traitsAt(traits_, 0)) != TOKEN_0_TRAITS) revert WrongTraitsContract();
  }

  function tokenImage(uint256 tokenId) external view returns (string memory) {
    return string.concat('data:image/svg+xml;base64,', Base64.encode(bytes(tokenSVG(tokenId))));
  }

  function tokenSVG(uint256 tokenId) public view returns (string memory) {
    (bytes memory head, Layout memory l) = _head();
    bytes16 punk = _traitBytes(head, l, tokenId);

    uint256[576] memory grid;
    uint32[11] memory keys = _layerKeys(tokenId, punk);
    for (uint256 i = 0; i < keys.length; i++) {
      if (keys[i] != 0) _draw(head, l, keys[i], grid);
    }

    return string(_toSVG(head, l, grid));
  }

  /**
   * @dev The 16 trait bytes for a token, as RadioactivePunksRenderer's
   *      getPunkDataAtOffset returns them.
   */
  function traitBytes(uint256 tokenId) external view returns (bytes16) {
    (bytes memory head, Layout memory l) = _head();
    return _traitBytes(head, l, tokenId);
  }

  struct Layout {
    uint256 palette;     // start of 3-byte RGB colors
    uint256 index;       // start of 8-byte layer index entries
    uint256 layerCount;
    uint256 tokens;      // start of u16 token IDs
    uint256 tokenCount;
    uint256 runs;        // start of 3-byte runs (end of `head`)
  }

  /**
   * @dev Copies everything before the runs (palette, layer index, token IDs)
   *      into memory and returns where each part starts.
   */
  function _head() private view returns (bytes memory head, Layout memory l) {
    uint256 colorCount = _u16(_read(0, 2), 0);
    l.palette = 2;
    l.index = l.palette + colorCount * 3 + 2;
    l.layerCount = _u16(_read(l.index - 2, 2), 0);
    l.tokens = l.index + l.layerCount * 8 + 2;
    l.tokenCount = _u16(_read(l.tokens - 2, 2), 0);
    l.runs = l.tokens + l.tokenCount * 2;
    head = _read(0, l.runs);
  }

  /**
   * @dev Copies `len` bytes starting at `from` of the packed layer data,
   *      which is split across layerData1 and layerData2.
   */
  function _read(uint256 from, uint256 len) private view returns (bytes memory out) {
    out = new bytes(len);
    uint256 first = from >= split ? 0 : (len < split - from ? len : split - from);
    address data1 = layerData1;
    address data2 = layerData2;
    uint256 boundary = split;
    assembly {
      // +1 skips each chunk's leading STOP byte
      if first { extcodecopy(data1, add(out, 32), add(from, 1), first) }
      if lt(first, len) {
        extcodecopy(data2, add(add(out, 32), first), add(sub(add(from, first), boundary), 1), sub(len, first))
      }
    }
  }

  function _traitsAt(address traits_, uint256 offset) private view returns (bytes32 word) {
    assembly {
      extcodecopy(traits_, 0, add(TRAITS_CODE_OFFSET, mul(offset, 15)), 15)
      word := and(mload(0), not(0xffffffffffffffffffffffffffffffffff))
    }
  }

  function _traitBytes(bytes memory head, Layout memory l, uint256 tokenId) private view returns (bytes16) {
    // token IDs are stored sorted, in the same order as the hyperstructure
    uint256 lo = 0;
    uint256 hi = l.tokenCount;
    while (lo < hi) {
      uint256 mid = (lo + hi) / 2;
      uint256 id = _u16(head, l.tokens + mid * 2);
      if (id == tokenId) return bytes16(_traitsAt(traits, mid));
      if (id < tokenId) lo = mid + 1;
      else hi = mid;
    }
    revert TokenDoesNotExist();
  }

  /**
   * @dev Port of the original renderer's JS layer selection. Returns layer
   *      keys in draw order; 0 means no layer.
   */
  function _layerKeys(uint256 tokenId, bytes16 punk) private pure returns (uint32[11] memory keys) {
    if (punk == bytes16(0)) return keys;

    uint256 glow = uint8(punk[GLOW]);
    uint256 mortality = uint8(punk[MORTALITY]);
    uint256 head = uint8(punk[HEAD]);
    bool oneOfOne = _isOneOfOne(tokenId);

    uint256 k = 0;
    for (uint256 o = 3; o < 15; o++) {
      if (o == 7) continue;
      uint256 n = uint8(punk[o]);
      if (o == 12 && n == 0) continue;

      uint256[4] memory parts = [o, n, 0xff, 0xff];
      if (o == 6) {
        uint256 color = uint8(punk[7]);
        if (n == 1) { parts[2] = color; parts[3] = glow; }
        if (n == 2) { parts[2] = color; }
      }
      if ((o == 13 && n != 12) || o == 11 || o == 9 || (o == 10 && n == 4)) parts[2] = glow;
      if (o == 3 && mortality == 0) parts[2] = 0;
      if (o == 12) { parts[1] = head; if (mortality == 0) parts[2] = 0; }
      if (o == 14) parts[0] = 15;

      keys[k++] = oneOfOne
        ? uint32(0xfe000000 | tokenId)
        : uint32((parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3]);
    }
  }

  function _isOneOfOne(uint256 tokenId) private pure returns (bool) {
    return tokenId == 698 || tokenId == 2536 || tokenId == 60 || tokenId == 370 || tokenId == 528
      || tokenId == 246 || tokenId == 420 || tokenId == 201 || tokenId == 1360 || tokenId == 878;
  }

  /**
   * @dev Paints a layer's runs into the grid. Grid cells hold color index + 1
   *      (0 = background). Layers with no art draw nothing, matching a
   *      `<use>` of a missing symbol in the original renderer.
   */
  function _draw(bytes memory head, Layout memory l, uint32 key, uint256[576] memory grid) private view {
    uint256 lo = 0;
    uint256 hi = l.layerCount;
    while (lo < hi) {
      uint256 mid = (lo + hi) / 2;
      uint256 entry = l.index + mid * 8;
      uint256 midKey = (_u16(head, entry) << 16) | _u16(head, entry + 2);
      if (midKey == key) {
        bytes memory runs = _read(l.runs + _u16(head, entry + 4) * 3, _u16(head, entry + 6) * 3);
        _paint(runs, 0, runs.length, grid);
        return;
      }
      if (midKey < key) lo = mid + 1;
      else hi = mid;
    }
  }

  // runs are 3 bytes: x:5 | y:5 | length:5 | colorIndex:9
  function _paint(bytes memory runs, uint256 from, uint256 to, uint256[576] memory grid) private pure {
    assembly {
      let data := add(runs, 32)
      for { let p := from } lt(p, to) { p := add(p, 3) } {
        let v := shr(232, mload(add(data, p)))
        let cell := add(mul(and(shr(14, v), 31), 24), shr(19, v))
        let end := add(cell, and(shr(9, v), 31))
        let color := add(and(v, 511), 1)
        for {} lt(cell, end) { cell := add(cell, 1) } {
          mstore(add(grid, shl(5, cell)), color)
        }
      }
    }
  }

  /**
   * @dev Writes the grid as horizontal runs, one <path> per color in order of
   *      first appearance (row-major). Writes whole words and advances by the
   *      text's length; bytes past the cursor are overwritten or cut off.
   */
  function _toSVG(bytes memory head, Layout memory l, uint256[576] memory grid) private pure returns (bytes memory out) {
    // runs packed as x | y << 8 | len << 16 | color << 24, never 0
    uint256[] memory runs = new uint256[](576);
    out = new bytes(MAX_SVG_LENGTH);
    bytes memory start = SVG_START;
    uint256 palette = l.palette;

    assembly {
      // ---- collect runs ----
      let runData := add(runs, 32)
      let runEnd := runData
      for { let y := 0 } lt(y, 24) { y := add(y, 1) } {
        let row := add(grid, mul(y, 768))
        let x := 0
        for {} lt(x, 24) {} {
          let c := mload(add(row, shl(5, x)))
          let len := 1
          for {} and(lt(add(x, len), 24), eq(mload(add(row, shl(5, add(x, len)))), c)) {} { len := add(len, 1) }
          if c {
            mstore(runEnd, or(or(x, shl(8, y)), or(shl(16, len), shl(24, c))))
            runEnd := add(runEnd, 32)
          }
          x := add(x, len)
        }
      }

      // ---- write SVG ----
      let ptr := add(out, 32)
      let startLen := mload(start)
      for { let i := 0 } lt(i, startLen) { i := add(i, 32) } {
        mstore(add(ptr, i), mload(add(add(start, 32), i)))
      }
      ptr := add(ptr, startLen)

      let hexChars := "0123456789abcdef"
      let colors := add(add(head, 32), palette)

      for { let r := runData } lt(r, runEnd) { r := add(r, 32) } {
        let first := mload(r)
        if first {
          let c := shr(24, first)

          mstore(ptr, '<path fill="#')
          ptr := add(ptr, 13)
          let rgb := shr(232, mload(add(colors, mul(sub(c, 1), 3))))
          for { let i := 0 } lt(i, 6) { i := add(i, 1) } {
            mstore8(add(ptr, i), byte(and(shr(sub(20, mul(i, 4)), rgb), 15), hexChars))
          }
          ptr := add(ptr, 6)
          mstore(ptr, '" d="')
          ptr := add(ptr, 5)

          for { let s := r } lt(s, runEnd) { s := add(s, 32) } {
            let run := mload(s)
            if eq(shr(24, run), c) {
              mstore(s, 0)
              let len := and(shr(16, run), 0xff)
              mstore8(ptr, 77) // M
              ptr := writeNum(add(ptr, 1), and(run, 0xff))
              mstore8(ptr, 32) // space
              ptr := writeNum(add(ptr, 1), and(shr(8, run), 0xff))
              mstore8(ptr, 104) // h
              ptr := writeNum(add(ptr, 1), len)
              mstore(ptr, 'v1h-')
              ptr := writeNum(add(ptr, 4), len)
              mstore8(ptr, 122) // z
              ptr := add(ptr, 1)
            }
          }

          mstore(ptr, '"/>')
          ptr := add(ptr, 3)
        }
      }

      mstore(ptr, '</svg>')
      ptr := add(ptr, 6)
      mstore(out, sub(ptr, add(out, 32)))

      // 0-24, so at most two digits
      function writeNum(p, n) -> next {
        if gt(n, 9) {
          mstore8(p, add(48, div(n, 10)))
          p := add(p, 1)
        }
        mstore8(p, add(48, mod(n, 10)))
        next := add(p, 1)
      }
    }
  }

  function _u16(bytes memory b, uint256 at) private pure returns (uint256) {
    return (uint256(uint8(b[at])) << 8) | uint8(b[at + 1]);
  }
}
